feat/WIT-224: Auto Standup
unswwit/discord-bot pull request #81
Opened 2024-11-10 11:32 UTC by ash1248

Auto Standup reminder for IT

2024-11-11 06:50 UTC, rbeccah requested changes, later dismissed
Good job on getting this working to send at a particular time! At the moment, we likely won't merge this into main because this is at MVP stage with quite a bit of hardcoding. 

Now that we have posts being able to be sent automatically , we will probably work on reducing the hardcoding which includes:
- Changing the channel_ID to be in whichever channel the command is run
- The day and hour which the standup runs is ideally inputted by the user
- All variables with `thursday` could be replaced with just `standup_day`

2024-11-11 06:50 UTC, rbeccah commented on cogs/auto_standup.py
> +channel_ID = 1172727647382552737
Just wondering, is this channel_ID hardcoded to the bot-testing-spam in WIT Willowbot?

2024-11-11 06:50 UTC, rbeccah commented on cogs/auto_standup.py
> +            if curr_time.weekday() == thursday and curr_time.hour == hour:
Instead of `thursday`, to avoid it seeming like it is hardcoded for the future, would change this to variable name to `day`

2024-11-11 06:50 UTC, rbeccah commented on cogs/auto_standup.py
> +day_seconds = 86400
Is `day_seconds` in relation to the number of seconds in a week? If so, make this should be changed to another variable name like `week_as_seconds` to make it clearer

2025-09-22 08:23 UTC, bmitanshi commented on cogs/auto_standup.py
> +        self.msg = "@Information Technology (IT) reminder to post standups ⭐"
Can you make the message more general so it can be used by other ports as well? 

Thanks!

2025-11-01 06:27 UTC, bmitanshi approved these changes
Great work! Feel free to merge it

2025-11-03 10:08 UTC, merged